compile: 
	javac -d ../bin src/Characters/* src/Controller/* src/gameModel/* src/Views/*

run: compile
	cd ../bin && java Controller.GameController

uncompress:
	jar cf project *.java

compress:
	jar xf project 
